# Generated by Django 6.0.3 on 2026-05-06 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='age_rating',
            field=models.CharField(choices=[('U', 'Universal (All Ages)'), ('UA', 'Parental Guidance'), ('13+', '13 Plus'), ('18+', 'Adults Only')], default='U', max_length=5),
        ),
        migrations.CreateModel(
            name='EpisodeAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_plays', models.PositiveIntegerField(default=0)),
                ('avg_listen_time', models.FloatField(default=0.0)),
                ('completion_rate', models.FloatField(default=0.0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('shares', models.PositiveIntegerField(default=0)),
                ('retention_data', models.JSONField(default=dict, help_text='Graph data for listener retention')),
                ('geographic_hits', models.JSONField(default=dict, help_text='Hits per city/region')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('episode', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='content.episode')),
            ],
        ),
    ]
