# Generated by Django 6.0.3 on 2026-06-13 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_show_age_rating_episodeanalytics'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('video_key', models.CharField(help_text='R2 storage key for teaser video', max_length=512)),
                ('thumbnail_key', models.CharField(blank=True, help_text='R2 storage key for teaser thumbnail', max_length=512)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teasers', to='content.show')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
    ]
