# Generated by Django 6.0.3 on 2026-06-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_teaser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='shows/thumbnails/'),
        ),
    ]
