# Generated by Django 6.0.3 on 2026-06-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_make_thumbnail_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='audio_file_key',
            field=models.CharField(blank=True, help_text='Cloudflare R2 storage key (path)', max_length=512),
        ),
    ]
