# Generated by Django 6.0.3 on 2026-07-12 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_teaser_redesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='show',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='show',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
