# Generated by Django 6.0.3 on 2026-07-12 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_episode_deleted_at_episode_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(help_text='Short code: en, hi, genz, etc.', max_length=10, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='languages/icons/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.AddField(
            model_name='episode',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodes', to='content.language'),
        ),
        migrations.AddField(
            model_name='show',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shows', to='content.language'),
        ),
    ]
