# Generated by Django 6.0.3 on 2026-07-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Login identifier for the employee', max_length=255, unique=True)),
                ('password', models.CharField(help_text='Hashed password for employee login', max_length=255)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('role_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='JSON object with resource: [actions] mapping')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee User',
                'verbose_name_plural': 'Employee Users',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
